### ISSUE TITLE
Ignite semaphore release vs. close

### ISSUE THREAD

**Issue by aarmam** [apache/ignite#10409]
Hi, 
I have a question about race condition on closing semaphores. As I understand semaphores are not removed automatically and must therfore be closed manually. Lets say two threads want to change some object and try to aquire semaphore for it: 

```java
IgniteSemaphore semaphore = ignite.semaphore(objectId, 1, true, true);
if (semaphore.tryAcquire(5, TimeUnit.SECONDS)) {
    try {
        changeObject(objectId);
    } finally {
        semaphore.release(); // First thread releases semaphore
        // Second thread aquires semaphore
        semaphore.close(); // First thread closes semaphore
    }
}
```
1) What happens if first thread tries to close semaphore while second thread has aquired it?
2) But my main quiestion is - can I close the semaphote without calling release before it? So second thread cannot aquire it.

**Comment by ptupitsyn** [comment]
1. It will be closed and removed from the cluster, even if acquired by other threads.
2. Yes, you can close without releasing.

In most cases you don't want to close a semaphore. You create it once and reuse.

**Comment by aarmam** [comment]
> In most cases you don't want to close a semaphore. You create it once and reuse.
Yes but in our case the changed object is relatively short lived and therefore aquired semaphore is always with unique id.
