### ISSUE TITLE
Question on loading data onto ignite

### ISSUE THREAD

**Issue by JDRanpariya** [apache/ignite#10469]
### What are various ways though which I can load data from Postgres table apart from using spark?
- I've tried reading data directly through Psycopg2 to Pyignite(thin client) but it seems slow and have parsing errors.
- I read data streamers are best for high speed transfer but is it possible to have streamer from Postgres(RDBMS) to ignite just for loading whole table using python? Its around 100k rows.

**Comment by ptupitsyn** [comment]
Python thin client does not have `DataStreamer` yet. But you should be able to achieve good performance with batched `putAll`. Instead of 100k `put` calls, try doing 100 `putAll` calls, 1000 items each. This is roughly what `DataStreamer` does.
