### ISSUE TITLE
should be id0 not id, ClusterGroup.forNodeId(UUID id, UUID... ids) in ClusterGroupAdapter.class

### ISSUE THREAD

**Issue by Rismer** [apache/ignite#10529]
https://github.com/apache/ignite/blob/3de1dc44f53ea510328badf6cb6b423fe6975bd8/modules/core/src/main/java/org/apache/ignite/internal/cluster/ClusterGroupAdapter.java#L461

should be
`if (contains(id0))`

**Comment by ptupitsyn** [comment]
Good catch, thank you!
Ticket filed: https://issues.apache.org/jira/browse/IGNITE-18766
