### ISSUE TITLE
disable or enable partition awareness from XML file for client node or thin client node.

### ISSUE THREAD

**Issue by virendar5Kmr** [apache/ignite#10532]
We are using java thin client in our spark streaming job and want to disable partition awareness in clinetConfigurtion class.

There is no option to pass that variable from XML file.

Please help

**Comment by ptupitsyn** [comment]
Use [ClientConfiguration#setPartitionAwarenessEnabled](https://ignite.apache.org/releases/latest/javadoc/org/apache/ignite/configuration/ClientConfiguration.html#setPartitionAwarenessEnabled-boolean-) to disable partition awareness. 

Can you please clarify what's the problem with XML?

**Comment by virendar5Kmr** [comment]
how to pass setPartitionAwarenessEnabled from xml file. I am not able to set this value to True or False from XML file.

**Comment by ptupitsyn** [comment]
@virendar5Kmr I don't know what kind of XML is used in your project. Assuming it is Spring XML:

```xml
    <bean id="igniteClient" class="org.apache.ignite.IgniteClientSpringBean">
        <property name="clientConfiguration">
            <bean class="org.apache.ignite.configuration.ClientConfiguration">
                <property name="addresses">
                    <list>
                        <value>127.0.0.1:10800</value>
                    </list>
                </property>
                <property name="partitionAwarenessEnabled" value="false" />
            </bean>
        </property>
    </bean>
```

**Comment by virendar5Kmr** [comment]
Thank you! @ptupitsyn, i try above. Yes it is Spring XML.
