### ISSUE TITLE
IgniteCluster: Discovery in the cloud document for Azure Blob storage refers to google compute java code sample

### ISSUE THREAD

**Issue by devansharora68** [apache/ignite#10542]
https://ignite.apache.org/docs/latest/clustering/discovery-in-the-cloud

In the above document the part for azure blob storage, the java code sample refers to google compute instead of a sample for azure example

![image](https://user-images.githubusercontent.com/52231935/219309859-6bfb8667-9e4a-4aa8-9b9c-afa670b1729b.png)

**Comment by ptupitsyn** [comment]
Ticket filed, thanks for reporting
https://issues.apache.org/jira/browse/IGNITE-18816
