### ISSUE TITLE
StopNodeOrHaltFailureHandler 

### ISSUE THREAD

**Issue by virendar5Kmr** [apache/ignite#10547]
StopNodeOrHaltFailureHandler.java

when we use StopNodeOrHaltFailureHandler it takes 10 to 15 minutes for JVM to kick in and kill the process due to critical error or system worker blocked.

How can we make sure jvm should kill it asap.

**Comment by shishkovilja** [comment]
@virendar5Kmr , what error caused the handler to be called? What version do you use?

**Comment by sk0x50** [comment]
Please check that `tryStop` flag is set to `false` value (this is the default) https://ignite.apache.org/releases/latest/javadoc/org/apache/ignite/failure/StopNodeOrHaltFailureHandler.html
