### ISSUE TITLE
Using Continuous Query with thin client causing OutOfMemoryError

### ISSUE THREAD

**Issue by hongchen2000** [apache/ignite#10559]
Using continuous query with thin clients(Java ignite version 2.14.0), resulted in OutOfMemoryError when one of the thin clients becomes slow. 

Tried to set SlowClientQueueLimit to 100 and MessageQueueLimit to 200, but seems it is not taking effect. The queue in GridSelectorNioSessionImpl continues to grow until run out of memory

**Comment by ptupitsyn** [comment]
Continuous Query [guarantees exactly-once delivery](https://ignite.apache.org/docs/latest/key-value-api/continuous-queries#events-delivery-guarantees). It can't just drop some events from the queue because the client is slow.

If the client performance can't be fixed, you have to come up with a different mechanism to receive updates (e.g. polling by "last_updated" or something like that).

**Comment by ptupitsyn** [comment]
Also check the answer here on continuous query buffer size tuning:

[[Ignite keeps crashing with OOM](https://stackoverflow.com/questions/75442184/ignite-keeps-crashing-with-oom)](https://stackoverflow.com/questions/75442184/ignite-keeps-crashing-with-oom)

**Comment by hongchen2000** [comment]
> Also check the answer here on continuous query buffer size tuning (`IGNITE_CONTINUOUS_QUERY_PENDING_BUFF_SIZE`, `IGNITE_CONTINUOUS_QUERY_SERVER_BUFFER_SIZE`):
> 
> [Ignite keeps crashing with OOM](https://stackoverflow.com/questions/75442184/ignite-keeps-crashing-with-oom)

In debugging my issue, these two parameters (IGNITE_CONTINUOUS_QUERY_PENDING_BUFF_SIZE, IGNITE_CONTINUOUS_QUERY_SERVER_BUFFER_SIZE) never went above 1. So they are not the cause and limiting them would not solve our problem

**Comment by hongchen2000** [comment]
SlowClientQueueLimit and MessageQueueLimit are working mechanism to deal with slow clients problem (drop them when they hung and stop processing messages): 
https://stackoverflow.com/questions/51092741/ignite-tcpcommunicationspi-can-slowclientqueuelimit-be-set-to-same-value-as-me

However, I think they are working only for thick clients, (but not for thin clients). 

The code is In the last two lines of GridNioServer.send0() method, where there is a check by msgQueueLsnr.apply(), which will call the GridNioServerWrapper.checkClientQueueSize(), which will drop the slow client if queue exceeds limit. 

Could we make the same mechanism working for thin client connections as well?

**Comment by ptupitsyn** [comment]
>  think they are working only for thick clients, (but not for thin clients).

That is correct. For now we don't have plans to adopt this mechanism for thin clients.

**Comment by petrov-mg** [comment]
@hongchen2000 The thin client outbound  message queue limit was introduced in [IGNITE-20424](https://issues.apache.org/jira/browse/IGNITE-20424) which is included in Ignite 2.16 release.

Thank you for filing this issue.
