### ISSUE TITLE
Embedding Ignite 3

### ISSUE THREAD

**Issue by renatoathaydes** [apache/ignite#10588]
I am trying to upgrade our codebase from Ignite 2 to 3. However, I cannot find any guides on how to do it.

We use the Java API.

Our Kotlin code looks something like this , currently:

```kotlin
import org.apache.ignite.*

// .. some config setup

           val igniteDiscoverySpi: DiscoverySpi = createDiscoverySpi(clusterConfiguration, configuration, ports)

            val config = ApacheIgniteConfiguration().apply {
                igniteInstanceName = configuration.id()
                localHost = "0.0.0.0"
                consistentId = configuration.serverInformation.id
                clientConnectorConfiguration = clientConnectorConfig
                discoverySpi = igniteDiscoverySpi
                communicationSpi = igniteCommunicationSpi
                isClientMode = false
                shutdownPolicy = ShutdownPolicy.GRACEFUL
                isPeerClassLoadingEnabled = false
                metricsLogFrequency = if (configuration.enableCacheStatistics) 30_000 else 0
                gridLogger = IgniteLoggerFactory.createLogger(configuration)
                workDirectory = distributedCacheWorkingDirectory(configuration.id())
                if (clusterConfiguration != null) {
                    sslContextFactory = TlsContextFactory(clusterConfiguration)
                }
            }

            val ignite = try {
                Ignition.start(config)
            } catch (e: IgniteException) {
                // error handling
            }
```

I am aware that the discovery mechanism, in particular, has changed a lot... but I cannot even find the `Ignite` class on version 3 (or most of other classes needed)... could you post code that's similar to the above for Ignite 3, or is there code somewhere I can look?

The documentation I found is currently nearly empty: : https://ignite.apache.org/docs/3.0.0-beta/

We know it's a beta version, but we need to release a feature in a few months that will use Ignite, and we want to see if Ignite 3 will work for our use case (we have had many issues with Ignite 2, specially regarding cluster discovery, and are hoping Ignite 3 will be helpful).

Anything you can provide to help us would be appreciated! Thanks.

**Comment by ptupitsyn** [comment]
Ignite 3 does not have a proper API for embedded mode yet. We are not sure if it should exist at all. Current idea is to provide client API only. 

>  we need to release a feature in a few months that will use Ignite, and we want to see if Ignite 3 will work for our use case

I think it might be too early to use Ignite 3 in prod at this point, let's wait for beta 2.
