### ISSUE TITLE
If we want to use Calcite,how should we choose between Ignite 2 and Ignite 3?

### ISSUE THREAD

**Issue by nwpuqyj** [apache/ignite#10627]
We are using Ignite 2.13.
Because of vulnerability scanning,H2 version of 1.4.197  needs to be upgraded.So we want to use Apache Calcite as SQL engine.we are confused about using Ignite 2 or Ignite 3 If we want to use calcite.
If we choose Ignite 2,we don't know the stability of Apache Calcite in Ignite 2；If we choose Ignite 3，we don't know release time of the stable version of Ignite 3.
Thanks~

**Comment by shishkovilja** [comment]
Hi @nwpuqyj ,
According to documentation, in 2.x it is still in beta state, but as I know it is stable enough, so you could check it in your test environment.
