### ISSUE TITLE
I want to know Binary Client how to use Transactions

### ISSUE THREAD

**Issue by lyonxh** [apache/ignite#10669]

**Comment by ptupitsyn** [comment]
Please clarify - what is a "Binary Client"?

**Comment by lyonxh** [comment]
Under the thin client

**Comment by lyonxh** [comment]
my project use go and i can only use this

**Comment by lyonxh** [comment]
![1682590416034](https://user-images.githubusercontent.com/77234741/234832882-739aba55-cd2d-48f3-ae40-cf88776120ae.png)

**Comment by lyonxh** [comment]
Yes thanks for your help, later we will consider developing our own go sdk similar to GORM, I think ignite is a good in-memory database very suitable for our business
