### ISSUE TITLE
I understand that ignite3 will unify the client protocol, and I would like to know how different the 3.x version of the protocol is from the 2.x version

### ISSUE THREAD

**Issue by lyonxh** [apache/ignite#10685]

**Comment by ptupitsyn** [comment]
2.x protocol: https://cwiki.apache.org/confluence/display/IGNITE/IEP-9+Thin+Client+Protocol
3.x protocol: https://cwiki.apache.org/confluence/display/IGNITE/IEP-76+Thin+Client+Protocol+for+Ignite+3.0
