### ISSUE TITLE
If I want to create a table, do I have to set a primary key, I don't want a primary key

### ISSUE THREAD

**Issue by lyonxh** [apache/ignite#10717]

**Comment by timoninmaxim** [comment]
Hi, which task are you solving? For table creation primary key is a required param. Table creates over underlying key-value cache. Table primary key is used as the key for the cache.

**Comment by lyonxh** [comment]
I have 2 tables, they are related, in the related table I need to use 2 fields uuid, one as the primary key of the related table, the other uuid as the related ID, I think this is very troublesome, so I want to ask if it is possible not to set the primary key of the table

**Comment by lyonxh** [comment]
I'm also considering maintaining the self-incrementing ids of the tables in my system's local cache, and I'm considering which option is more appropriate
