### ISSUE TITLE
 Apache Ignite Table support  Schemaless ？

### ISSUE THREAD

**Issue by siaron** [apache/ignite#10746]
Apache Ignite Table  usage supports Schemaless ？. For example, columns are automatically created when writing. More common in IoT scenarios

**Comment by ptupitsyn** [comment]
Yes, our key-value API is schemaless.

More info:
* https://ignite.apache.org/docs/latest/key-value-api/basic-cache-operations
* https://ignite.apache.org/docs/latest/key-value-api/binary-objects

**Comment by siaron** [comment]
When using the Table API, will there be a large performance loss if adding or deleting a column （DDL）?

**Comment by ptupitsyn** [comment]
Adding or deleting a column with SQL API should be fairly quick, because it does not modify the data. The data is always stored in schemaless format (key/value pairs). 

For example:


```csharp
using Apache.Ignite.Core;
using Apache.Ignite.Core.Cache.Configuration;
using Apache.Ignite.Core.Cache.Query;

var ignite = Ignition.Start();

var cfg = new CacheConfiguration("c", new QueryEntity(typeof(Person)));
var cache = ignite.GetOrCreateCache<int, Person>(cfg);
cache[1] = new Person(1, "Foo", 123);

Query("SELECT * FROM PERSON");
Query("ALTER TABLE Person ADD COLUMN Age INT");
Query("SELECT * FROM PERSON");
Query("ALTER TABLE Person DROP COLUMN Age");

// "Age" value is not affected by DDL.
Console.WriteLine("Person = " + cache[1]);

void Query(string sql)
{
    Console.WriteLine(" >>> " + sql);

    using var cursor = cache.Query(new SqlFieldsQuery(sql));

    foreach (var name in cursor.FieldNames)
    {
        Console.Write($"{name}\t");
    }

    Console.WriteLine();

    foreach (var row in cursor)
    {
        foreach (var val in row)
        {
            Console.Write($"{val}\t");
        }
    }

    Console.WriteLine();
    Console.WriteLine();
}

// Initial configuration does not include SQL Age column.
public record Person(
    [property: QuerySqlField] int Id,
    [property: QuerySqlField] string Name,
    int Age);
```

**Comment by siaron** [comment]
if using UPDATE set some filed value, Will ignite internally re-write the value of the entire object? Will there be a problem with write amplification?

**Comment by ptupitsyn** [comment]
It will modify only the specified field. This may require rewriting the entire object if the new value is of different size.

**Comment by ptupitsyn** [comment]
The data is stored in serialized form (think byte array). Ignite knows the offset of every field in this byte array. Only the modified field will be updated, other fields are not deserialized/serialized.

**Comment by siaron** [comment]
Use the key, value api to operate the table, how to update the schema of the table after dynamically adding columns

**Comment by siaron** [comment]
```java
  BinaryObject obj = sqlPublicDevice.get("c20110");
```
If this key contains many fields, will BinaryObject transfer the entire byte to the client?

**Comment by ptupitsyn** [comment]
> BinaryObject obj = sqlPublicDevice.get("c20110");

I don't understand this code.

`BinaryObject` can contain any number of fields, including nested objects of any depth.
