### ISSUE TITLE
Apache ignite failing on statup

### ISSUE THREAD

**Issue by MjdBh** [apache/ignite#10759]
I am trying mapp a field but getting this error on startup 

`Caused by: class org.apache.ignite.IgniteCheckedException: Failed to create page store work directory: /home/user/apache-ignite/work/db/0_0_0_0_0_0_0_1_lo_10_0_0_100_10_0_0_203_10_99_0_5_127_0_0_1_198_18_0_1_198_18_0_129_198_18_0_65_198_18_2_1_2604_3d09_679_2b00_0_0_0_1dc7_wlp0s20f3_2604_3d09_679_2b00_8332_15b9_3cd0_484_wlp0s20f3_2604_3d09_679_2b00_ae91_a1ff_fe7e_63ba_enxac91a17e63ba_2604_3d09_679_2b00_d986_6638_3c47_cd7c_wlp0s20f3_2604_3d09_679_2b00_e8bf_ac63_b39_630e_enxac91a17e63ba_47501
	at org.apache.ignite.internal.util.IgniteUtils.ensureDirectory(IgniteUtils.java:9971)
	at org.apache.ignite.internal.processors.cache.GridLocalConfigManager.<init>(GridLocalConfigManager.java:127)
	at org.apache.ignite.internal.processors.cache.GridCacheProcessor.start(GridCacheProcessor.java:618)
	at org.apache.ignite.internal.IgniteKernal.startProcessor(IgniteKernal.java:1784)
	... 11 more
Failed to start grid: Failed to start processor: GridProcessorAdapter []`

**Comment by ptupitsyn** [comment]
Can you share full stack trace - there should be the root cause deeper down?

The same question appears on StackOverflow: https://stackoverflow.com/questions/76387714/apache-ignit-failin-on-startup . Please respect the community and avoid duplicate questions.

**Comment by sk0x50** [comment]
The answer was provided on StackOverflow mentioned by Pavel ^
