### ISSUE TITLE
.NET library for integrating with NHibernate

### ISSUE THREAD

**Issue by satishviswanathan** [apache/ignite#10785]
Just wanted to check if there is any initiative to add support for integrating with NHibernate

**Comment by ptupitsyn** [comment]
We don't plan to integrate with NHibernate. Ignite.NET has built-in ORM capabilities: https://ignite.apache.org/docs/latest/net-specific/net-linq

**Comment by satishviswanathan** [comment]
@ptupitsyn  , thank you for sharing the info. I'm relatively new to ignite and still trying to figure it out.  Appreciate your help.

**Comment by satishviswanathan** [comment]
@ptupitsyn  I can see a library for entity framework library as well. Does both serve the same purpose ?

**Comment by ptupitsyn** [comment]
[Entity Framework](https://www.nuget.org/packages/Apache.Ignite.EntityFramework) provides second-level cache for the legacy EF on .NET Framework. It is a different thing.
