### ISSUE TITLE
GridDiagnostic warning while starting ignite 2.15.0

### ISSUE THREAD

**Issue by rajsolanki73** [apache/ignite#10803]
I see this following in log.

`[2023-06-23T13:10:31,168][WARN ][pub-#21][GridDiagnostic] Initial heap size is 248MB (should be no less than 512MB, use -Xms512m -Xmx512m).
`

in https://github.com/apache/ignite/blob/master/modules/core/src/main/java/org/apache/ignite/internal/GridDiagnostic.java i see 

long initBytes = ManagementFactory.getMemoryMXBean().getHeapMemoryUsage().getInit();

I understand its warning but to get rid it what settings what changes i should make in my shell scripts ? 

I m using binary install.

**Comment by sk0x50** [comment]
This message means that the size of the heap (the amount of memory in bytes that the Java virtual machine initially requests from the operating system for memory management) is less than 512Mb. It is assumed that Apache Ignite requires at least 512Mb.

Please take a look at the following page [Java Heap and GC Tuning](https://ignite.apache.org/docs/latest/perf-and-troubleshooting/memory-tuning#java-heap-and-gc-tuning)

Also, you can find the description of `Xms` and `Xmx` options here [Java Options](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html#BABHDABI)
