### ISSUE TITLE
Connection configuration for control.sh in Kubernetes

### ISSUE THREAD

**Issue by fenixcitizen** [apache/ignite#10834]
Up until Apache Ignite 2.14 it was possible to use Visor console to connect to a cluster using Spring XML configuration file as documented at https://github.com/apache/ignite/blob/2.14.0/modules/visor-console/src/main/scala/org/apache/ignite/visor/commands/VisorConsole.scala#L91 It was useful for Kubernetes deployments as we use `TcpDiscoveryKubernetesIpFinder`.

How do I do the same with `control.sh` script that is supposed to replace Apache Ignite Visor functionality going forward? I would like to be able to inspect caches stats.

**Comment by sk0x50** [comment]
The possible ways to workaround this issue were discussed on the user list: https://lists.apache.org/thread/91ps451yy9rl2g4zqjnd27ns63zn35nx
