### ISSUE TITLE
Is there a function to obtain hotkeys implemented

### ISSUE THREAD

**Issue by lvchongyi** [apache/ignite#10836]
I want to obtain get hotkeys, do you have this feature?

**Comment by sk0x50** [comment]
Hi @lvchongyi ,

There is no such API.
It is unclear what the goal is and what you are trying to achieve, but anyway, the following two topics might be useful:

- you can try to enable ignite events and build a list of "hot keys" on your side based on keys in cache events. [Working with Events](https://ignite.apache.org/docs/latest/events/listening-to-events)
 - please take a look at near caches. this feature allows creation of a local cache that stores the most recently or most frequently accessed data on the local node. [Near Caches](https://ignite.apache.org/docs/latest/configuring-caches/near-cache)
