### ISSUE TITLE
How to custom the port 10800 and port 47500

### ISSUE THREAD

**Issue by Shoothzj** [apache/ignite#10851]
Hello, community.

I am newbie to ignite. I want to know how to custom the port `10800` or port `47500`. I have figured out port `11211` can be customed by `ConnectorConfiguration port`

Thanks in advance, any help would be greateful :)

**Comment by ptupitsyn** [comment]
* `10800` is [ClientConnectorConfiguration#port](https://ignite.apache.org/releases/latest/javadoc/org/apache/ignite/configuration/ClientConnectorConfiguration.html#setPort-int-)
* `47500` is [TcpDiscoverySpi#localPort](https://ignite.apache.org/releases/latest/javadoc/org/apache/ignite/spi/discovery/tcp/TcpDiscoverySpi.html#setLocalPort-int-)

**Comment by Shoothzj** [comment]
@ptupitsyn Thanks for your reply, I thought `11211` is default ClientConnectorConfiguration#port, could you please tell me what's the port `47100` and `11211`? Thank you in advance.

**Comment by ptupitsyn** [comment]
* `11211` is JDBC
* `47100` is [TcpCommunicationSpi](https://ignite.apache.org/releases/latest/javadoc/org/apache/ignite/spi/communication/tcp/TcpCommunicationSpi.html#DFLT_PORT)

**Comment by Shoothzj** [comment]
Thanks @ptupitsyn :)
