### ISSUE TITLE
ARM / Apple Silicon Docker image

### ISSUE THREAD

**Issue by Renkas** [apache/ignite#10876]
Could we get image that works natively on Apple Silicon (`linux/arm64/v8`)?

Currently there is only `linux/amd64` available in Docker Hub.

Or is there a specific reason/blocker that it has not been done yet?

**Comment by ptupitsyn** [comment]
There should be no blockers, Ignite is known to work on ARM natively.

@Renkas I've built a multi-arch image and pushed to https://hub.docker.com/r/ptupitsyn/ignite/tags, can you please test it on Apple Silicon? If it works, I'll make the required changes to our code and build procedure.

**Comment by ptupitsyn** [comment]
Multi-arch image build steps:
* Install [Docker buildx](https://www.baeldung.com/ops/docker-buildx)
* Change base image from **alpine** to **focal**: https://github.com/apache/ignite/pull/10877
* Download release binaries into https://github.com/apache/ignite/tree/master/deliveries/docker/apache-ignite directory
* Run `docker buildx build . -f ./x86_64/Dockerfile -t ptupitsyn/ignite:2.15.0 -t ptupitsyn/ignite:latest --push --platform linux/amd64,linux/arm64` (in the same dir)

**Comment by Renkas** [comment]
Image loaded up fine and is running now without rosetta translation layer. Can't really test it further as my use case needs v2.14.0. But I'm sure it would work fine.

**Comment by ptupitsyn** [comment]
#10877 merged; `-arm64` tags pushed to Docker hub for Ignite 2.15.

@Renkas I think I can also build and push those tags for 2.14 - do you need that?

**Comment by gmuth** [comment]
This doc here https://ignite.apache.org/docs/latest/quick-start/java says:  x86, x64, SPARC, PowerPC

**Comment by smaurya52** [comment]
> #10877 merged; `-arm64` tags [pushed to Docker hub for Ignite 2.15](https://hub.docker.com/r/apacheignite/ignite/tags).
> 
> @Renkas I think I can also build and push those tags for 2.14 - do you need that?

Can you please build and push the image for 2.14 arm64 as well. Thank you :)

**Comment by ptupitsyn** [comment]
> Can you please build and push the image for 2.14 arm64 as well. Thank you :)

Pushed:
* [2.14.0-jdk11-arm64](https://hub.docker.com/layers/apacheignite/ignite/2.14.0-jdk11-arm64/images/sha256-1e593930a102cd45d45abb212552d5c484e8a9539dc900028fb771e3bab88762?context=explore)
* [2.14.0-arm64](https://hub.docker.com/layers/apacheignite/ignite/2.14.0-arm64/images/sha256-28e621c82169af6d674d1d41481f6704520478c3176e7061ebe24cdb995785d6?context=explore)

**Comment by smaurya52** [comment]
> > Can you please build and push the image for 2.14 arm64 as well. Thank you :)
> 
> Pushed:
> 
> * [2.14.0-jdk11-arm64](https://hub.docker.com/layers/apacheignite/ignite/2.14.0-jdk11-arm64/images/sha256-1e593930a102cd45d45abb212552d5c484e8a9539dc900028fb771e3bab88762?context=explore)
> * [2.14.0-arm64](https://hub.docker.com/layers/apacheignite/ignite/2.14.0-arm64/images/sha256-28e621c82169af6d674d1d41481f6704520478c3176e7061ebe24cdb995785d6?context=explore)

Thanks you so much :)

**Comment by sumitahuja17** [comment]
2.14.0-arm64 does not work with custom host port. Ignite client is able to discover the node but when simple "hello word" compute is done, it throws "message failed for node id", whereas simply changing the host port mapping from 47502:47500 to 47500:47500. On the emded client side I tried using both MultiCast IP finder and VImipfinder with the right ports, but it just don't work. Suspecting it is image issue.
