### ISSUE TITLE
Is there any StaticIpFinder impl for Ignite Discovery

### ISSUE THREAD

**Issue by shoothzj** [apache/ignite#10893]
Hello, community. I'm currently exploring Ignite and was wondering if it supports a discovery mechanism for static IPs, especially in the context of Kubernetes' StatefulSet. Any guidance or references would be greatly appreciated.

Thank you for your time and assistance!

**Comment by ggjtm** [comment]
This looks like a question best suited for a community discussion forum, and the question is definitely open-ended and not actionable issue. I recommend closing this issue.

https://ignite.apache.org/our-community.html#faq
