### ISSUE TITLE
 Access to Ignite Internal tasks is restricted 

### ISSUE THREAD

**Issue by 1ssqq1lxr** [apache/ignite#10907]
version: Ignite 2.15.0

source code:
This code runs fine in 2.14.0

 @Override
    public <R> Collection<R> callBroadcast(JobCaller<R> callable) {
        try {
            IgniteCallable<R> igniteCallable = callable::call;

            return igniteCompute.broadcast(igniteCallable);
        } catch (Exception e) {
       
            return Collections.emptySet();
        }
    }
debug:
GridTaskWorker:
private void authorizeSystemTaskJob(ComputeJob job) {
        if (!ctx.security().isSystemType(task.getClass()))
            return;

        Object executable = unwrap(job);

        if (!ctx.security().isSystemType(executable.getClass())) {
            assert opts.isPublicRequest();

            ctx.security().authorize(executable.getClass().getName(), TASK_EXECUTE);
        }
        else if (executable instanceof PlatformSecurityAwareJob)
            ctx.security().authorize(((PlatformSecurityAwareJob)executable).name(), TASK_EXECUTE);
        else if (opts.isPublicRequest()) {
            if (executable instanceof PublicAccessJob)
                authorizeAll(ctx.security(), ((PublicAccessJob)executable).requiredPermissions());
            else {
                // We do not allow to execute internal tasks via public API for security reasons.
                throw new SecurityException("Access to Ignite Internal tasks is restricted" +
                        " [task=" + task.getClass().getName() + ", job=" + job.getClass() + "]");
            }
        }
    }

**Comment by petrov-mg** [comment]
Hello, @1ssqq1lxr

1. What exactly problem are you facing? 
2. Could you attach the stacktrace if there is one? 
3. What Ignite Compute task are you trying to perform and what API are you using to run it? 
4. Could you please attach the configuration you are using to start the Ignite instance? (The most important part is the security configuration. Are you using the built-in authentication mechanism or your own security implementation?)

It also would be very helpful if you attach a minimal reproducer of your problem.

**Comment by 1ssqq1lxr** [comment]
1. Cluster connection is OK

2. A customized broadcast task executed by each node in the cluster



Why does the GridTaskWorker check report an error?

**Comment by 1ssqq1lxr** [comment]
DataStorageConfiguration dataStorageConfiguration = new DataStorageConfiguration();
        dataStorageConfiguration.setDataRegionConfigurations(getDataRegionConfigurations(
                bootstrapConfig.getStoreConfig().getStoreType() == StoreType.LOCAL,
                IgniteCacheRegion.values()));
        IgniteConfiguration igniteConfiguration = new IgniteConfiguration();
        igniteConfiguration.setAsyncCallbackPoolSize(Runtime.getRuntime().availableProcessors()/2);
        igniteConfiguration.setDataStorageConfiguration(dataStorageConfiguration);
        String localAddress = Optional.ofNullable(clusterConfig.getLocalAddress()).orElse(ServerUtils.serverIp);
        igniteConfiguration.setLocalHost(localAddress);
        igniteConfiguration.setAuthenticationEnabled(false);
        igniteConfiguration.setConnectorConfiguration(new ConnectorConfiguration().setHost(localAddress));
        igniteConfiguration.setGridLogger(new Slf4jLogger());
        if (StringUtils.isNotEmpty(clusterConfig.getWorkDirectory())) {
            igniteConfiguration.setWorkDirectory(clusterConfig.getWorkDirectory());
        } else {
            igniteConfiguration.setWorkDirectory(System.getProperty("user.home"));
        }
        igniteConfiguration.setClientMode(false);
        TcpDiscoverySpi spi = new TcpDiscoverySpi();
        if (clusterConfig.getAddresses() != null) {
            TcpDiscoveryVmIpFinder ipFinder = new TcpDiscoveryVmIpFinder();
            // ip集群
            ipFinder.setAddresses(clusterConfig.getAddresses());
            spi.setIpFinder(ipFinder);
        } else {
            TcpDiscoveryMulticastIpFinder ipFinder = new TcpDiscoveryMulticastIpFinder();
            // 组播
            String multicastGroup = clusterConfig.getMulticastGroup();
            if (multicastGroup != null) {
                ipFinder.setMulticastGroup(multicastGroup);
            }
            Integer multicastPort = clusterConfig.getMulticastPort();
            if (multicastPort != null) {
                ipFinder.setMulticastPort(multicastPort);
            }
            spi.setIpFinder(ipFinder);
        }

        igniteConfiguration.setDiscoverySpi(spi);

**Comment by petrov-mg** [comment]
> Why does the GridTaskWorker check report an error? 

Could you please attach stacktrace of the "error" you mentioned?

> customized broadcast task

What does "customized" mean? Could you please attach the code of your task?

**Comment by 1ssqq1lxr** [comment]
public class IgniteExecutor implements JobExecutor {

    private final IgniteCompute igniteCompute;


    public IgniteExecutor(IgniteCompute igniteCompute) {
        this.igniteCompute = igniteCompute;
    }


    @Override
    public void execute(Job job) {
        try {
            IgniteRunnable runnable = job::run;
            if (job.isBroadcast()) {
                igniteCompute.broadcast(runnable);
            } else {
                igniteCompute.run(runnable);
            }
        } catch (Exception e) {
            ContextHolder.getReceiveContext()
                    .getLogManager()
                    .printError(null, LogEvent.CLUSTER, job.getJobName()+" execute  error "+e.getMessage());
        }

    }


    @Override
    public <R> Collection<R> callBroadcast(JobCaller<R> callable) {
        try {
            IgniteCallable<R> igniteCallable = callable::call;

            return igniteCompute.broadcast(igniteCallable);
        } catch (Exception e) {
            ContextHolder.getReceiveContext()
                    .getLogManager()
                    .printError(null, LogEvent.CLUSTER, callable.getJobName()+" callBroadcast  error "+e.getMessage());
            return Collections.emptySet();
        }

    }

    @Override
    public <INPUT, OUT> Collection<OUT> callBroadcast(JobClosure<INPUT, OUT> callable, INPUT input) {
        try {
            return this.igniteCompute.broadcast(callable, input);
        } catch (Exception e) {
            ContextHolder.getReceiveContext()
                    .getLogManager()
                    .printError(null, LogEvent.CLUSTER, callable.getJobName()+" callBroadcast error "+e.getMessage());
            return Collections.emptySet();
        }
    }


    @Override
    public <R> R call(JobCaller<R> callable) {
        try {
            IgniteCallable<R> igniteCallable = callable::call;
            return igniteCompute.call(igniteCallable);
        } catch (Exception e) {
            ContextHolder.getReceiveContext()
                    .getLogManager()
                    .printError(null, LogEvent.CLUSTER, callable.getJobName()+" call error "+e.getMessage());
            return null;
        }
    }

}

**Comment by 1ssqq1lxr** [comment]
public Collection<Map<String,String>> getClusterInfo() {
        return ContextHolder.getReceiveContext()
                    .getIntegrate().getJobExecutor()
                    .callBroadcast(new JobCaller<Map<String,String>>() {
                        @Override
                        public Map<String,String> call() throws Exception {
                            BootstrapConfig bootstrapConfig = ContextHolder.getReceiveContext().getConfig();
                            Map<String,String> map = new HashMap<>();
                            map.put("ip",Optional.ofNullable(bootstrapConfig.getClusterConfig().getLocalAddress()).orElse(ServerUtils.serverIp ));
                            String httpUrl =bootstrapConfig.getHttpConfig().getHost() + ":" + bootstrapConfig.getHttpConfig().getPort();
                            if (bootstrapConfig.getHttpConfig().getSsl() != null) {
                                map.put("httpAddress","https://" +httpUrl);
                            } else {
                                map.put("httpAddress","http://" +httpUrl);
                            }
                            return map;
                        }

                        @Override
                        public String getJobName() {
                            return "getClusterInfo";
                        }
                    });
    }

**Comment by 1ssqq1lxr** [comment]
This code runs on 2.14.0 without any issues. On 2.15.0, an error message was reported, and I have also posted the error message on it

**Comment by petrov-mg** [comment]
> an error message was reported, and I have also posted the error message on it

Could you please attach the **stacktrace** and not just the error message.
It should look something like this:

```
class org.apache.ignite.IgniteException: Access to Ignite Internal tasks is restricted [task=org.apache.ignite.internal.processors.closure.GridClosureProcessor$T6, job=class org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2]
	at org.apache.ignite.internal.util.lang.RunnableX.run(RunnableX.java:40)
	at org.apache.ignite.common.ComputeTaskPermissionsTest.assertFailed(ComputeTaskPermissionsTest.java:549)
	at org.apache.ignite.common.ComputeTaskPermissionsTest.checkCallable(ComputeTaskPermissionsTest.java:511)
	at org.apache.ignite.common.ComputeTaskPermissionsTest.checkTaskStart(ComputeTaskPermissionsTest.java:347)
	at org.apache.ignite.common.ComputeTaskPermissionsTest.testNode(ComputeTaskPermissionsTest.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.apache.ignite.testframework.junits.GridAbstractTest$6.run(GridAbstractTest.java:2504)
	at java.lang.Thread.run(Thread.java:750)
Caused by: class org.apache.ignite.plugin.security.SecurityException: Access to Ignite Internal tasks is restricted [task=org.apache.ignite.internal.processors.closure.GridClosureProcessor$T6, job=class org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2]
	at org.apache.ignite.internal.processors.task.GridTaskWorker.authorizeSystemTaskJob(GridTaskWorker.java:1786)
	at org.apache.ignite.internal.processors.task.GridTaskWorker.processMappedJobs(GridTaskWorker.java:595)
	at org.apache.ignite.internal.processors.task.GridTaskWorker.body(GridTaskWorker.java:533)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:125)
	at org.apache.ignite.internal.processors.task.GridTaskProcessor.startTask(GridTaskProcessor.java:753)
	at org.apache.ignite.internal.processors.task.GridTaskProcessor.execute(GridTaskProcessor.java:448)
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor.callAsync(GridClosureProcessor.java:369)
	at org.apache.ignite.internal.IgniteComputeHandler.broadcastAsync(IgniteComputeHandler.java:362)
	at org.apache.ignite.internal.IgniteComputeImpl.broadcast(IgniteComputeImpl.java:282)
	at org.apache.ignite.common.ComputeTaskPermissionsTest.lambda$checkTaskStart$13(ComputeTaskPermissionsTest.java:347)
	at org.apache.ignite.common.ComputeTaskPermissionsTest.lambda$checkCallable$9d5e5b8f$3(ComputeTaskPermissionsTest.java:511)
	at org.apache.ignite.internal.util.lang.RunnableX.run(RunnableX.java:37)
	... 14 more
```
Without **stacktrace** it's very hard to understand what's going on.

I even locally tested the project you are developing - https://github.com/quickmsg/smqttx (I hope I'm not mistaken and the code snippets mentioned above were based on this source). I upgraded the Ignite dependency to 2.15, launched `io.github.quickmsg.jar.JarStarter` and successfully ran the command to get information about the cluster `http://localhost:60000/smqtt/cluster`. I could not reproduce the problem you mentioned.

If any other steps are required to reproduce the problem, feel free to describe them.

**Comment by petrov-mg** [comment]
Oh. Got it. You are using `maven-assembly-plugin` to repackage Ignite JARs and your project's JARs in one Uber-JAR

```
<plugin>
    <artifactId>maven-assembly-plugin</artifactId>
    <configuration>
        <appendAssemblyId>false</appendAssemblyId>
        <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
        </descriptorRefs>
        <archive>
            <manifest>
                <mainClass>io.github.quickmsg.jar.JarStarter</mainClass>
            </manifest>
        </archive>
    </configuration>
    <executions>
        <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
                <goal>single</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

As a result, Ignite treats your project's classes as Ignite internals and unconditionally applies security checks to them.

You can try to avoid using Uber-JAR to solve this problem. Are there good reasons why you need Uber-JAR?

In any case, I'll see if we can improve the security check in this case.

Tank you for reporting this issue.

**Comment by 1ssqq1lxr** [comment]
Thank you. We hope to resolve this issue in the future. Currently, we are using Overwrite GridTaskWorker to ignore this exception

**Comment by please-fix-vulnerability** [comment]
Hi, I am just commenting that we also are facing this issue. We downgraded to ignite version 2.14.0 to stop the issue from appearing. Please keep this thread updated with any fixes in later ignite versions

**Comment by shnus** [comment]
Hi @petrov-mg,

We are facing the same issue. 

Uber(Fat) JAR may not be the best, but it is a fair deployment option. And the fact that compute tasks don't work is frustrating...

It seems that the problem lies in the IgniteSecurityAdapter#isSystemType implementation. We are relying on Class#ProtectionDomain#CodeSource to identify if a task is from Ignite sources or not. Unfortunately, the fat JAR overrides code source for classes, and Ignite is considering all tasks as system tasks. Perhaps, a safer option would be to provide path analysis to identify system tasks?

What do you think?

**Comment by 1ssqq1lxr** [comment]
> > an error message was reported, and I have also posted the error message on it
> 
> Could you please attach the **stacktrace** and not just the error message. It should look something like this:
> 
> ```
> class org.apache.ignite.IgniteException: Access to Ignite Internal tasks is restricted [task=org.apache.ignite.internal.processors.closure.GridClosureProcessor$T6, job=class org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2]
> 	at org.apache.ignite.internal.util.lang.RunnableX.run(RunnableX.java:40)
> 	at org.apache.ignite.common.ComputeTaskPermissionsTest.assertFailed(ComputeTaskPermissionsTest.java:549)
> 	at org.apache.ignite.common.ComputeTaskPermissionsTest.checkCallable(ComputeTaskPermissionsTest.java:511)
> 	at org.apache.ignite.common.ComputeTaskPermissionsTest.checkTaskStart(ComputeTaskPermissionsTest.java:347)
> 	at org.apache.ignite.common.ComputeTaskPermissionsTest.testNode(ComputeTaskPermissionsTest.java:221)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.apache.ignite.testframework.junits.GridAbstractTest$6.run(GridAbstractTest.java:2504)
> 	at java.lang.Thread.run(Thread.java:750)
> Caused by: class org.apache.ignite.plugin.security.SecurityException: Access to Ignite Internal tasks is restricted [task=org.apache.ignite.internal.processors.closure.GridClosureProcessor$T6, job=class org.apache.ignite.internal.processors.closure.GridClosureProcessor$C2]
> 	at org.apache.ignite.internal.processors.task.GridTaskWorker.authorizeSystemTaskJob(GridTaskWorker.java:1786)
> 	at org.apache.ignite.internal.processors.task.GridTaskWorker.processMappedJobs(GridTaskWorker.java:595)
> 	at org.apache.ignite.internal.processors.task.GridTaskWorker.body(GridTaskWorker.java:533)
> 	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:125)
> 	at org.apache.ignite.internal.processors.task.GridTaskProcessor.startTask(GridTaskProcessor.java:753)
> 	at org.apache.ignite.internal.processors.task.GridTaskProcessor.execute(GridTaskProcessor.java:448)
> 	at org.apache.ignite.internal.processors.closure.GridClosureProcessor.callAsync(GridClosureProcessor.java:369)
> 	at org.apache.ignite.internal.IgniteComputeHandler.broadcastAsync(IgniteComputeHandler.java:362)
> 	at org.apache.ignite.internal.IgniteComputeImpl.broadcast(IgniteComputeImpl.java:282)
> 	at org.apache.ignite.common.ComputeTaskPermissionsTest.lambda$checkTaskStart$13(ComputeTaskPermissionsTest.java:347)
> 	at org.apache.ignite.common.ComputeTaskPermissionsTest.lambda$checkCallable$9d5e5b8f$3(ComputeTaskPermissionsTest.java:511)
> 	at org.apache.ignite.internal.util.lang.RunnableX.run(RunnableX.java:37)
> 	... 14 more
> ```
> 
> Without **stacktrace** it's very hard to understand what's going on.
> 
> I even locally tested the project you are developing - https://github.com/quickmsg/smqttx (I hope I'm not mistaken and the code snippets mentioned above were based on this source). I upgraded the Ignite dependency to 2.15, launched `io.github.quickmsg.jar.JarStarter` and successfully ran the command to get information about the cluster `http://localhost:60000/smqtt/cluster`. However, I could not reproduce the problem you mentioned.
> 
> If any other steps are required to reproduce the problem, feel free to describe them.

Will this problem be fixed in subsequent versions? Currently testing the latest 2.16.0, this problem still exists。

**Comment by petrov-mg** [comment]
The described issue was fixed fixed in [IGNITE-21216](https://issues.apache.org/jira/browse/IGNITE-21216) which will be available in the next Apache Ignite release.

Tank you for reporting this issue.
