### ISSUE TITLE
Changing data expiry at runtime

### ISSUE THREAD

**Issue by fbutter** [apache/ignite#10911]
The current documentation states that the cache configuration cannot be changed. In the wiki I found the page [https://cwiki.apache.org/confluence/display/IGNITE/Allow+Configuration+Settings+Change+At+Runtime ](Allow Configuration Settings Change At Runtime).

- Is the topic of changing the cache configuration at runtime still on your agenda?
- Was changing the data expiry at runtime one candidate?
- Is there a way to set or modify the TTL, used by the "[single thread to clean up expired entries in the background](https://ignite.apache.org/docs/latest/configuring-caches/expiry-policies#eager-ttl)"?

Thank you very much

**Comment by sk0x50** [comment]
Hello @fbutter ,

> Is the topic of changing the cache configuration at runtime still on your agenda?
I don't think so, unfortunately. I could not find any discussions on the dev list that relate to this topic, at least.

> Is there a way to set or modify the TTL, used by the "[single thread to clean up expired entries in the background](https://ignite.apache.org/docs/latest/configuring-caches/expiry-policies#eager-ttl)"?
It can be done programmatically using `IgniteCache.withExpiryPolicy` method https://ignite.apache.org/releases/latest/javadoc/org/apache/ignite/IgniteCache.html#withExpiryPolicy-javax.cache.expiry.ExpiryPolicy- This method returns cache with the specified expired policy set. This policy will be used for each operation invoked on the returned cache.
