### ISSUE TITLE
running mvn with java 11

### ISSUE THREAD

**Issue by karunakar0** [apache/ignite#10984]
Hi 
i am trying to run mvn using
mvn -pl modules/core test -Dtest=org.apache.ignite.internal.storage.pagememory.PageMemoryImplTest#testReadBeforeInitialize

I set mvn java version to 11 and java/Home version also set to 11 but its not woking it shows it should be run in java version 11 or higher.

**Comment by ptupitsyn** [comment]
The command `mvn -pl modules/core test -Dtest=org.apache.ignite.internal.storage.pagememory.PageMemoryImplTest#testReadBeforeInitialize` works for me, and I only have JDK 11.

Please double check your `JAVA_HOME` environment variable and make sure `java -version` returns `11`.
