### ISSUE TITLE
Ignite\Work folder is getting saved to the path "C:\Windows\System32\ignite\work\log" after dotnet6 upgrade of the project

### ISSUE THREAD

**Issue by Indupa** [apache/ignite#11005]
Hi,

i have **ApacheIgniteService** project where latest apache ignite 2.15 is consumed to use to run as Ignite service as background windows service. we will be creating NuGet package out of this project and consuming it one of our application to install this and run as windows service as **"ApacheIgniteService"**

earlier when our ApacheIgniteService project was with .net 4.8 framework , this Ignite\work\logs folder used to get creating at root level ( Directory inside application where we have installed Service") like example : If my application name is **xxxx**  and installed service folder in it is "**ApacheIgniteService** ", then this log files are getting saved into the path : **"xxxx\ApacheIgniteService\Ignite\work\logs"**.

But now when we upgraded our ApacheIgniteService  project to .net 6 framework and trying to run as service , this Ignite\work\logs folder is getting created under **"C:\Windows\System32\ignite\work\log"** by default , any specifc reason on this....?

Could you please help us how do we change this path to make it point to root level which was there earlier....?

**Comment by ptupitsyn** [comment]
Have you tried setting [IgniteConfiguration.WorkDirectory](https://ignite.apache.org/releases/latest/dotnetdoc/api/Apache.Ignite.Core.IgniteConfiguration.html#Apache_Ignite_Core_IgniteConfiguration_WorkDirectory) property?
