### ISSUE TITLE
JMX AttributeList does not contain Attributes

### ISSUE THREAD

**Issue by simon-greatrix** [apache/ignite#11045]
When supplying JMX information, the AttributeList class should contain Attributes, however the existing code returns attribute values. This can cause ClassCastExceptions in code that attempts to read an AttributeList. 

Please see the my pull request for a proposed resolution.

**Comment by sk0x50** [comment]
Hello @simon-greatrix ,

At first glance, the proposed patch looks valid to me. Anyway, I'll take a closer look at your code. Thank you for reporting this issue!

**Comment by skanikdale** [comment]
Hello @sk0x50,

We are looking for this fix for exposing Ignite cache metrics.  Could you please share info about timelines and versions in which this fix can be incorporated?

**Comment by NSAmelchev** [comment]
Hi, @skanikdale , The patch was cherry picked to the 2.16. The release planned for the next two weeks.
