### ISSUE TITLE
Apache Ignite 2.16 not working with Java v17

### ISSUE THREAD

**Issue by MdKamranUddin** [apache/ignite#11267]
Hi All,

The use case is we are upgrading our Spring Boot project which is using Ignite dependency from Java v8 to Java v17 and have put all the jvm args mentioned in the documentation as well and using the 2.16 version of Ignite in the pom.xml but its still giving the below error--
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @15761df8

Please help anyone if there are any working fix for this.

Thanks & Regards,
Kamran
Note: Can't put the full stack trace as working in a Client VDI

**Comment by ptupitsyn** [comment]
You have to pass some additional JVM args, see:
* https://ignite.apache.org/docs/latest/quick-start/java#running-ignite-with-java-11-or-later
* https://stackoverflow.com/questions/75359894/apache-ignite-support-for-java-17
