### ISSUE TITLE
Continuous query using NodeJS client

### ISSUE THREAD

**Issue by satishviswanathan** [apache/ignite#11312]
I'm relatively  new to this software and still playing around to figure out how the features are working. I came across continuous query  and was curious to know if the nodejs client supports it.  Thank you in advance.

https://ignite.apache.org/docs/latest/key-value-api/continuous-queries#examples

**Comment by sk0x50** [comment]
Hi @satishviswanathan ,

Unfortunately, Node.js thin client does not support Continuous Queries.

You can find additional information about using Ignite Node.js thin client here: [Node.js Thin Client](https://ignite.apache.org/docs/latest/thin-clients/nodejs-thin-client)
A complete list of supported features can be found here: [Thin clients features](https://cwiki.apache.org/confluence/display/IGNITE/Thin+clients+features)

**Comment by satishviswanathan** [comment]
@sk0x50 thank you for your response. That was helpful
