### ISSUE TITLE
we need go client sdk

### ISSUE THREAD

**Issue by Linuxlovers** [apache/ignite#11313]
We need to use the go language to connect to the gnite database. Could you please support the development of the go client? Thank you

**Comment by ptupitsyn** [comment]
There is a third-party Ignite client: https://github.com/amsokol/ignite-go-client

Even though it has not been updated for some time, it should still work with latest Ignite versions, because client protocol is backwards-compatible.

**Comment by Linuxlovers** [comment]
I didn't see any support for transactions in this third-party package. Assuming the transaction statement is as follows
BEGIN TRANSACTION;
 
UPDATE account SET balance=balance -100 WHERE id=1;
Update account SET balance=balance+100 WHERE id=2;
 
COMMIT;

can  i directly use c Is it executed using the QuerySQLFields method?

**Comment by ptupitsyn** [comment]
https://ignite.apache.org/docs/2.15.0/sql-reference/transactions

**Comment by shishkovilja** [comment]
@ptupitsyn , @Linuxlovers , transactional SQL was removed since 2.16.

**Comment by Linuxlovers** [comment]
So, after removing the transaction, are there any other usage scenarios for this in memory database?

**Comment by ptupitsyn** [comment]
> are there any other usage scenarios for this in memory database?

1. It is not only in-memory, you can enable persistence or use third-party storage
2. All other use cases are available, such as SQL, caching, Compute
3. There is also a [RESTful API](https://ignite.apache.org/docs/latest/restapi#execute-a-task)
4. Finally, if something is missing in the Go SDK or RESTful API, you can always implement it as a Java compute task and call that from Go or any other language. Consider Java as our DSL.

**Comment by ptupitsyn** [comment]
@Linuxlovers a new Go client was just released by a third party: https://gitverse.ru/sbertech/ignite-go-client

No transactions yet, but I hear that they are coming soon.

**Comment by Linuxlovers** [comment]
I can't register for that platform. Can you please ask them to support SQL and transactions as soon as possible

**Comment by lyonxh** [comment]
in this third-party client,i can't set key expire time

**Comment by lyonxh** [comment]
none rust sdk too

**Comment by lyonxh** [comment]
may be i can use TiDB
