### ISSUE TITLE
IBinarizable : Mapping complex objects

### ISSUE THREAD

**Issue by satishviswanathan** [apache/ignite#11325]
I'm still new to ignite and trying to see how saving of complex object works. I was following the implementation using the interface IBinarizable  as mentioned in the link below, However the attributes of Address type is not getting saved to Employee table.

https://ignite.apache.org/docs/latest/net-specific/net-serialization

In the above link I saw the below statement. CAn someone explain what does that mean and is that the reason why I'm not seeing the Address not saved to the backend table?

_IBinarizable can also be implemented in raw mode, without field names. This provides the fastest and the most compact serialization, but disables SQL queries:_

**Comment by ptupitsyn** [comment]
If you use `GetRawWriter`, it will work with key/value API, but not with SQL.

> the attributes of Address type is not getting saved to Employee table

Please share the code. What do you mean by "not getting saved to Employee table" - how do you see that?

**Comment by satishviswanathan** [comment]
@ptupitsyn Thank you for your response. This is what I have been trying to do.

DDL statement. I have created the following table by executing the DDL statement from Database Manager (DBeaver).

```
CREATE TABLE IF NOT EXISTS employee (
  id int,
name varchar,
companyid varchar,
age int,
city varchar,
street varchar,
streetnumber int,
flatnumber int,
  PRIMARY KEY (id)
) WITH "template=partitioned,backups=1,WRITE_SYNCHRONIZATION_MODE=FULL_SYNC,CACHE_GROUP=Employee,CACHE_NAME=Employee,KEY_TYPE=int,VALUE_TYPE=Employee";
```


_After that I have executed the following program to create an employee record , however the address details are not getting saved_ 
[ignite-sample.zip](https://github.com/apache/ignite/files/15078729/ignite-sample.zip)

_Employee Table view_

![image](https://github.com/apache/ignite/assets/17437409/82593162-df5e-44d0-a8b0-8033ac60ff06)

**Comment by ptupitsyn** [comment]
`Address.WriteBinary` uses `GetRawWriter`, which does not work with SQL.

Basically there is no mapping between field names and values, just some bytes, Ignite does not know where the `City` value is an so on.

Fix `Address` class to use `IBinaryWriter` with field names like you do in `Employee`.

P.S. When sharing code, please avoid including binaries (`bin`, `obj`).

**Comment by satishviswanathan** [comment]
@ptupitsyn Thank you for your help.
 I did try as shown in example but let me check again. One difference was I started as a Ignite client. I'm still trying to figure out the difference between Ignite.Start() and Ignite.StartClient(). That was one difference from what I did when compared to the example.

**Comment by ptupitsyn** [comment]
> still trying to figure out the difference between Ignite.Start() and Ignite.StartClient()

* `Ignition.Start()` creates an embedded *server* node, which becomes a part of the cluster, stores data, executes computations, etc. This is a powerful mode but may require a lot of resources.
* `Ignition.StartClient()` starts a lightweight *thin client*. It has some limitations compared to embedded mode, but is a lot quicker to start, does not require Java and consumes little resources

We recommend the thin client by default, but the API is very similar and you can switch back and forth if the requirements change.

**Comment by satishviswanathan** [comment]
@ptupitsyn Thank you that cleared by confusions.

However this issue still persist, the Address fields are not updated. Although the data is not serialized to these fields, I can see the values are there in the cache. Is it because while creating the table using the ddl statement we have the VALUE_TYPE as Employee and the ignite server is unware of the "Address"  type ?

Attaching the sample code with the updated implementation
[ignite-sample.zip](https://github.com/apache/ignite/files/15120307/ignite-sample.zip)

**Comment by ptupitsyn** [comment]
Adding `address object` column to your DDL script fixes the issue. 

SQL engine does not drill down the nested object if there is no matching column.

**Comment by satishviswanathan** [comment]
**_DL statement._**

CREATE TABLE IF NOT EXISTS synim_tab.employee (
  id int,
name varchar,
companyid varchar,
age int,
city varchar,
street varchar,
streetnumber int,
flatnumber int,
  PRIMARY KEY (id)
) WITH "template=partitioned,backups=1,WRITE_SYNCHRONIZATION_MODE=FULL_SYNC,CACHE_GROUP=Employee,CACHE_NAME=Employee,KEY_TYPE=int,VALUE_TYPE=Employee";

What would be the data type of address ?If I add address as a column then how are this fields of address (city, streetnumber, flatnumber) going to be mapped ?

**Comment by ptupitsyn** [comment]
```sql
CREATE TABLE IF NOT EXISTS employee (
  id int,
  name varchar,
  address object,
  companyid varchar,
  age int,
  city varchar,
  street varchar,
  streetnumber int,
  flatnumber int,
  PRIMARY KEY (id)
) WITH "template=partitioned,backups=1,WRITE_SYNCHRONIZATION_MODE=FULL_SYNC,CACHE_GROUP=Employee,CACHE_NAME=Employee,KEY_TYPE=int,VALUE_TYPE=Employee";
```

Just add `address object` column and run your code, it will work.
