### ISSUE TITLE
In ignite2.16.0 and jdk21, run task with lambda expression, it can not run.

### ISSUE THREAD

**Issue by nelsoncaoGithub** [apache/ignite#11352]
run task code is
`public <T> Future<T> submit(Callable<T> task) {
ClusterGroup scheduler = ignite.cluster().forPredicate(SCHEDULE_SELECTOR);
      return CompletableFuture.supplyAsync(() -> ignite.compute(scheduler)
         .call(task::call));
   }
`

exception:
ava.util.concurrent.ExecutionException: class org.apache.ignite.IgniteException: Remote job threw user exception (override or implement ComputeTask.result(..) method if you would like to have automatic failover for this exception): Task was not deployed or was redeployed since task execution [taskName=IgniteCluster$$Lambda/0x000001fea2626ca0, taskClsName=IgniteCluster$$Lambda/0x000001fea2626ca0, codeVer=0, clsLdrId=06c5fc07f81-837412f5-916c-4d3e-acf7-7706853a9be5, seqNum=1715584588896, depMode=SHARED, dep=null]

 Ignite relies on the class name of the corresponding anonymous inner class when executing Lambda expressions. 

![image](https://github.com/apache/ignite/assets/38907307/21d4f056-9751-4533-b3a2-194b52e2c09b)

In JDK 21, the class name of corresponding anonymous inner class is changed
        java 17 Main$$Lambda$14/0x0000000800066840
        java 21 Main$$Lambda/0x0000023d4e003400

so IgniteUtils#lambdaEnclosingClassName() logic should adjust.

**Comment by sk0x50** [comment]
Hi @nelsoncaoGithub ,

Thank you for pointing this out! It looks like the issue is fixed, please take a look at https://issues.apache.org/jira/browse/IGNITE-22952
