### ISSUE TITLE
Question: Apache ignite on kubernetes with Proxy

### ISSUE THREAD

**Issue by ratadepally** [apache/ignite#11367]
Hi,

We are currently working on apache Ignite to onboard on Kubernetes cluster. The issue here is Kubernetes cluster node IPs changes dynamically all the time and there is no way that the client will know which IP to connect using thin or thick client approach. Is there any standard for using proxy on top of Ignite cluster or is there any specific document that suggests to use proxy instead of individual IP to connect through client.

Thanks for any suggestions in advance.

**Comment by ptupitsyn** [comment]
Have you tried `TcpDiscoveryKubernetesIpFinder`?
https://ignite.apache.org/releases/latest/javadoc/org/apache/ignite/spi/discovery/tcp/ipfinder/kubernetes/TcpDiscoveryKubernetesIpFinder.html

**Comment by ratadepally** [comment]
Hi @ptupitsyn thanks for the suggestion on TcpDiscoveryKubernetesIpFinder. I will explore that option for kubernetes Ignite cluster.
