### ISSUE TITLE
Question: CacheStore Configuration using DDL

### ISSUE THREAD

**Issue by ratadepally** [apache/ignite#11363]
Hi,

We are currently working on creating cache using the Ignite DDL statements and came across a scenario where we need to map the cache data to external Database like postgres.  We tried using the xml Config and Java based code but what we are looking for is if there is any way we can configure already existing cache which was created using DDL and add the CacheJDBCBlobStore config change without bringing the nodes down or downtime. Please let us know if this possible?

Any suggestions will be helpful. thanks

**Comment by ptupitsyn** [comment]
It is not possible to change cache store configuration for an existing cache. 

Zero downtime workaround is to create a new cache with a different configuration, copy the data, drop the old cache.

**Comment by ratadepally** [comment]
thank you for the response @ptupitsyn. 

1. With respect to CacheJDBCBlobStore do we need to deploy the POJO class for key and value Objects we use for cache persistence or entries as we cannot peer class load these models. And if we don't upload these classes on each server we are getting below ERROR.

 **class org.apache.ignite.binary.BinaryInvalidTypeException: x.x.x.MyClass** and **java.lang.ClassNotFoundException: x.x.x.MyClass**

2. Can we make use of **UriDeploymentSpi** to deploy the model classes on Ignite servers? or is there any other option to do so without the need for stopping all nodes and manually uploading these classes and starting them again?

Any suggestions will be helpful thanks.

**Comment by ptupitsyn** [comment]
1. Yes, POJO classes need to be deployed on all servers
2. I'm not sure about UriDeploymentSpi

**Comment by ratadepally** [comment]
@ptupitsyn - thank you for the response
