### ISSUE TITLE
Ignite cluster discovery

### ISSUE THREAD

**Issue by satishviswanathan** [apache/ignite#11372]
@ptupitsyn - on apache client is there a way I can mention a service discovery url in the connection string rather than give multiple nodes in the cluster?

**Comment by ptupitsyn** [comment]
Service discovery URLs are not supported directly, but you can implement your own "address finder" that will load the addresses from the URL and pass to the Ignite client:

https://ignite.apache.org/releases/latest/javadoc/org/apache/ignite/configuration/ClientConfiguration.html#setAddressesFinder-org.apache.ignite.client.ClientAddressFinder-
