### ISSUE TITLE
ignite-kafka not found in the optional/modules

### ISSUE THREAD

**Issue by Taymindis** [apache/ignite#11418]
Is ignite Kafka still supporting? I can't find this module from the [docs](https://ignite.apache.org/docs/latest/extensions-and-integrations/streaming/kafka-streamer#streaming-data-via-kafka-connect)

**Comment by Taymindis** [comment]
Does anyone have idea ?

**Comment by shishkovilja** [comment]
@Taymindis , `ignite-kafka` was moved to Apache Ignite Extensions repository: https://github.com/apache/ignite-extensions/tree/master/modules/kafka-ext. Currently, there are no new releases of this extensions.

**Comment by Taymindis** [comment]
@shishkovilja Noted, i will use latest ignite-kafka-ext with latest ignite libs to make it work. Thanks
