### ISSUE TITLE
Eviction is not Happening for dataregion persistence=true 

### ISSUE THREAD

**Issue by kagrawal-tibco** [apache/ignite#11463]
We want limited cache functionality for persistence = true and data should be evicted as per PageReplacement policy used . But currently data is not evicting and project throws outOfMemoryException.

 I am attaching the sample project/class  to depict the same You can use the project or simply change the cacheTrasaction example file in ignite examples and change the  REGION_40MB_EVICTION = "40MB_Region_Eviction" in example-data-regions.xml config file to enable persistence and page Replacement policy. 
This is created by modifying one of Ingite's shipped examples : cacheTrasactionExample.java class and the example-data-regions.xml to enable persistence. You can see for persistence disabled it is working fine  and can see from logs data is evicting properly if cache.put() call is used.

-----------------------------------------------------------------------------------------------------------------------------------------
persistence =true ,pageReplacementMode = SEGMENTED_LRU 

>>> Cache transaction example started.
DatastorageConfig40MB_Region_Eviction SEGMENTED_LRU0.9 null
DatastorageConfig30MB_Region_Swapping CLOCK0.9 null
[2024-08-03T11:34:16,656][ERROR][checkpoint-runner-cpu-#97][] Critical system error detected. Will be handled accordingly to configured handler [hnd=StopNodeOrHaltFailureHandler [tryStop=false, timeout=0, super=AbstractFailureHandler [ignoredFailureTypes=UnmodifiableSet [SYSTEM_WORKER_BLOCKED, SYSTEM_CRITICAL_OPERATION_TIMEOUT]]], failureCtx=FailureContext [type=CRITICAL_ERROR, err=class o.a.i.i.mem.IgniteOutOfMemoryException: Out of memory in data region [name=40MB_Region_Eviction, initSize=12.0 MiB, maxSize=15.0 MiB, persistenceEnabled=true] Try the following:
  ^-- Increase maximum off-heap memory size (DataRegionConfiguration.maxSize)
  ^-- Enable eviction or expiration policies]]
org.apache.ignite.internal.mem.IgniteOutOfMemoryException: Out of memory in data region [name=40MB_Region_Eviction, initSize=12.0 MiB, maxSize=15.0 MiB, persistenceEnabled=true] Try the following:
  ^-- Increase maximum off-heap memory size (DataRegionConfiguration.maxSize)
  ^-- Enable eviction or expiration policies
	at org.apache.ignite.internal.processors.cache.persistence.pagemem.PageMemoryImpl.allocatePage(PageMemoryImpl.java:654) ~[ignite-core-2.15.0.jar:2.15.0]
-------------------------------------------------------------------------------------------------------------------------------------
persistence = false
>>> Accounts a deposit: 
>>> Account [id=1, balance=$100.0]
>>> Account [id=2, balance=$200.0]

>>> Accounts after transfer: 
>>> Account [id=20, balance=$100.0]
>>> null
>>> Cache transaction example finished.

>>> Accounts after transfer: 
>>> Account [id=20, balance=$100.0]
>>> Account [id=1005, balance=$100.0]
>>> Cache transaction example finished.

>>> Accounts after transfer: 
>>> Account [id=20, balance=$100.0]
>>> Account [id=1005, balance=$100.0]
>>> Cache transaction example finished.

>>> Accounts after transfer: 
>>> null
>>> null
>>> Cache transaction example finished.

```

**Comment by kagrawal-tibco** [comment]
[LimitedCache.zip](https://github.com/user-attachments/files/16478343/LimitedCache.zip)

**Comment by ptupitsyn** [comment]
Eviction does not work with native persistence, see https://ignite.apache.org/docs/latest/memory-configuration/eviction-policies

> Eviction is used in following cases:
> * for off-heap memory when [Native Persistence](https://ignite.apache.org/docs/latest/persistence/native-persistence) is off;
> * for off-heap memory when Ignite is used with an [external storage](https://ignite.apache.org/docs/latest/persistence/external-storage);
> * for [on-heap caches](https://ignite.apache.org/docs/latest/configuring-caches/on-heap-caching);
> * for [near caches](https://ignite.apache.org/docs/latest/configuring-caches/near-cache) if configured.

> When Native Persistence is on, a similar process — called page replacement — is used to free up off-heap memory when Ignite > cannot allocate a new page. The difference is that the data is not lost (because it is stored in the persistent storage), and  > therefore you are less concerned about losing data than about efficiency. Refer to the [Replacement Policies](https://ignite.apache.org/docs/latest/memory-configuration/replacement-policies) page for information about page replacement configuration.

**Comment by kagrawal-tibco** [comment]
Hi @ptupitsyn  thank you for the quick response if you see I have enabled the page replacement policy as well in the config file. the policy used is SEGMENTED_LRU.

**Comment by ptupitsyn** [comment]
You are right, did not notice this initially. I've tried your code and it fails for me too.

I think 40 MB is just too small for page replacement to work properly - there are not enough pages overall.

If I change `maxSize` to 400 MB, the error does not occur, and we can see that there is more data on disk than in RAM:

```
[12:19:33]     ^--   40MB_Region_Eviction region [type=user, persistence=true, lazyAlloc=true,
[12:19:33]       ...  initCfg=100MB, maxCfg=400MB, usedRam=392MB, freeRam=1.95%, allocRam=400MB, allocTotal=886MB]
```

**Comment by kagrawal-tibco** [comment]
Thank you for your response yes for higher memory it works with 100 MB .

**Comment by ptupitsyn** [comment]
You can probably achieve a lower limit by making the [page size](https://ignite.apache.org/docs/latest/persistence/persistence-tuning#adjusting-page-size) smaller.

Can I ask you - what is the use case? Ignite is made for big data, a 40 MB data region might be suboptimal.

**Comment by kagrawal-tibco** [comment]
Sorry for late response .We have ignite integration with our product and We give our customers to set the cache size and we wanted to confirm what is the minimum size after which there is no error . So updated that to a higher value for now

**Comment by kagrawal-tibco** [comment]
Thanks @ptupitsyn For all the help
