### ISSUE TITLE
Forcefully specify the number of CPUs

### ISSUE THREAD

**Issue by pycgo** [apache/ignite#11472]
^-- Cluster [hosts=1, CPUs=1, servers=1

Is there an environment variable that can set the number of machine CPUs perceived by IGNITE? Due to the inability to set CPU limit on cgroup1 and newer versions k8s, the number of CPUs obtained by IGNITE will always be 1，but The K8S machine has 8 CPUs。

**Comment by ptupitsyn** [comment]
Cgroups should work, I'm not sure about "inability to set CPU limit"

```sh
> docker run apacheignite/ignite
... CPUs=20 ...

> docker run --cpus 2 apacheignite/ignite
... CPUs=2 ...
```

**Comment by pycgo** [comment]
in centos7 cgroup1 && k8s 1.28, k8s yaml can not set cpu request limit ,and in alamalinux9 cgroup2 && k8s 1.28 +,everything is ok

**Comment by ptupitsyn** [comment]
Ok, I see.

> Is there an environment variable that can set the number of machine CPUs perceived by IGNITE

No, there is no such thing in Ignite. The closes thing is thread pool config: https://ignite.apache.org/docs/latest/perf-and-troubleshooting/thread-pools-tuning.

**Comment by pycgo** [comment]
> Ok, I see.
> 
> > Is there an environment variable that can set the number of machine CPUs perceived by IGNITE
> 
> No, there is no such thing in Ignite. The closes thing is thread pool config: https://ignite.apache.org/docs/latest/perf-and-troubleshooting/thread-pools-tuning.

Can these threads utilize all CPUs or only one CPU at a time ？ when log print ^-- Cluster [hosts=1, CPUs=1, servers=1 ？

For example, as far as I know, ES has a similar configuration and is very effective in avoiding cgroup problems
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html#node.processors
![image](https://github.com/user-attachments/assets/e09fc6d8-8dfc-403a-93de-6a3ac7f0a222)

**Comment by ptupitsyn** [comment]
> when log print ^-- Cluster [hosts=1, CPUs=1

This comes from the JVM, which gets it from the OS, so the answer is no. The OS won't allow the process to utilize more CPUs.
