### ISSUE TITLE
Question - Events vs Continuous query

### ISSUE THREAD

**Issue by ratadepally** [apache/ignite#11529]
Hi

We are currently working on a use case where we will need data modifications events for cache to be triggered and sent to the listener or handler and inside the registered listener we will be performing operations to update or insert data into another Cache.

For the above use case we came across below two options.
1. Ignite Events
2. Continuous query

i)  Out of these two contenders would you suggest any approach?
ii) which one guarantees event updates to be delivered even in case of any primary node failures?
iii) which is more resilient in case of clustering? 
iv) Are there any drawbacks of using one over the other especially with performance?

Any suggestions are greatly appreciated.

**Comment by ptupitsyn** [comment]
The answer is Continuous Query, it has built-in resiliency, batching, exactly-once delivery guarantee.

Events are better suited for things like observability and diagnostics.

**Comment by ratadepally** [comment]
> The answer is Continuous Query, it has built-in resiliency, batching, exactly-once delivery guarantee.
> 
> Events are better suited for things like observability and diagnostics.

Thank you for your response @ptupitsyn.
