### ISSUE TITLE
Question: DateTime Conversion Issue with different server

### ISSUE THREAD

**Issue by ratadepally** [apache/ignite#11546]
Hi 

We are currently facing an issue with Date Time Conversion function. We used below query to convert Date time string to timestamp.

SELECT CONVERT('2022-09-09 00:00:00', TIMESTAMP);

When we ran the query on Server1(Ubuntu Linux Server) it gave us below output.

![image](https://github.com/user-attachments/assets/545a0c84-607e-4db1-bcc0-cc33c79a6ceb)

and when we ran same query on Server2(Oracle Linux Server ) it gave different result.

![image](https://github.com/user-attachments/assets/3459059f-924e-408a-8eb8-eaf5cb38fc43)

What we are expecting here is for the date to not change as we are just converting Date String to Timestamp.

Does Server distro really matter with these type of Ignite date conversion? Please suggest

**Comment by ratadepally** [comment]
Hi - Any suggestions or comments on this please?

**Comment by ygerzhedovich** [comment]
@ratadepally It doesn't matter which distro you used. It just Java application which run in JVM. What here can be matter - it's timezone on both of servers or parameters JVM related to timezone.

**Comment by ratadepally** [comment]
Hi @ygerzhedovich - thank you for the update.
